name: Unzip shell.zip and remove archive

on:
  push:
    paths:
      - '**/shell.zip'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: unzip-shell-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Ensure unzip is available
        shell: bash
        run: |
          set -Eeuo pipefail
          if ! command -v unzip >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y unzip
          fi

      - name: Extract all shell.zip files and remove archives
        shell: bash
        run: |
          set -Eeuo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global safe.directory "$GITHUB_WORKSPACE"

          changes=0

          # Find and process all shell.zip files anywhere in the repo
          while IFS= read -r -d '' z; do
            echo "Processing: $z"

            # Derive output directory next to the archive (e.g., ./path/shell.zip -> ./path/shell)
            dir="${z%.*}"
            mkdir -p "$dir"

            # Extract; if unzip fails, the job exits before deletion (due to set -e)
            unzip -o "$z" -d "$dir"

            # Remove the archive from git if tracked; otherwise from filesystem
            if git rm --quiet -- "$z"; then
              echo "Removed tracked archive: $z"
            else
              rm -f -- "$z"
              echo "Removed untracked archive: $z"
            fi

            # Stage extracted content
            git add -A -- "$dir"
            changes=1
          done < <(find . -type f -name 'shell.zip' -print0)

          if [ "$changes" -eq 0 ]; then
            echo "No shell.zip files found — nothing to do."
            exit 0
          fi

          # Only commit if there are staged changes
          if git diff --staged --quiet; then
            echo "No staged changes to commit."
            exit 0
          fi

          git commit -m "Unzip shell.zip into companion directories and remove archives [skip ci]"
          git push
